In [1]:
# Dependencies and setup
import pandas as pd
import os
import glob

In [2]:
#Files to load
college_football_data = '../source_data/cfb*.csv'

In [3]:
all_files = glob.glob(college_football_data)

In [4]:
df = (pd.read_csv(f) for f in all_files)

In [5]:
dataframes_list = []

In [6]:
for x in all_files:
    temp_df = pd.read_csv(x)
    dataframes_list.append(temp_df)

In [7]:
#for dataset in dataframes_list:
    #display(dataset)

In [8]:
#Show Just 1 Dataset from the DataFrame
display(dataframes_list[1])

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Total.TDs,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
0,Akron (MAC),12,5,7,88,891,4479,5.03,32,33,...,29:05,76,11,13,24,12,14,26,-2,-0.17
1,Alabama (SEC),14,12,2,17,1018,6783,6.66,67,68,...,31:45,71,9,11,20,12,10,22,-2,-0.14
2,Arizona (Pac-12),14,10,4,25,1139,6491,5.70,55,61,...,27:13,26,13,13,26,8,10,18,8,0.57
3,Arizona St. (Pac-12),13,10,3,34,975,5750,5.90,54,59,...,28:42,6,13,14,27,4,9,13,14,1.08
4,Arkansas (SEC),13,7,6,60,916,5278,5.76,52,56,...,34:02,27,12,12,24,11,6,17,7,0.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,Washington St. (Pac-12),12,3,9,7,1014,6210,6.12,50,50,...,31:29,123,5,3,8,7,18,25,-17,-1.42
109,West Virginia (Big 12),13,7,6,12,1097,6497,5.92,44,49,...,29:52,119,2,12,14,19,10,29,-15,-1.15
110,Western Ky. (C-USA),13,8,5,4,986,6950,7.05,70,76,...,28:05,37,10,13,23,8,10,18,5,0.38
111,Western Mich. (MAC),13,8,5,39,875,5696,6.51,55,57,...,32:46,48,10,13,23,10,10,20,3,0.23
112,Wisconsin (Big Ten),14,11,3,21,970,6564,6.77,61,61,...,33:38,110,11,6,17,10,16,26,-9,-0.64

In [9]:
#Convert one of the Lists into a Dataframe
df_2013=pd.DataFrame(dataframes_list[1])

In [10]:
#Print the Dataframe
df_2013.head(100)

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Total.TDs,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
0,Akron (MAC),12,5,7,88,891,4479,5.03,32,33,...,29:05,76,11,13,24,12,14,26,-2,-0.17
1,Alabama (SEC),14,12,2,17,1018,6783,6.66,67,68,...,31:45,71,9,11,20,12,10,22,-2,-0.14
2,Arizona (Pac-12),14,10,4,25,1139,6491,5.70,55,61,...,27:13,26,13,13,26,8,10,18,8,0.57
3,Arizona St. (Pac-12),13,10,3,34,975,5750,5.90,54,59,...,28:42,6,13,14,27,4,9,13,14,1.08
4,Arkansas (SEC),13,7,6,60,916,5278,5.76,52,56,...,34:02,27,12,12,24,11,6,17,7,0.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Tulsa (AAC),12,2,10,56,958,4950,5.17,34,37,...,31:34,111,7,8,15,5,18,23,-8,-0.67
96,UAB (C-USA),12,6,6,42,941,5182,5.51,44,52,...,30:33,76,10,9,19,9,12,21,-2,-0.17
97,UCF (AAC),13,9,4,99,942,4727,5.02,42,43,...,31:53,66,10,18,28,14,15,29,-1,-0.08
98,UCLA (Pac-12),13,10,3,22,992,6082,6.13,50,55,...,29:09,59,5,11,16,10,6,16,0,0.00
99,UConn (AAC),12,2,10,123,736,3315,4.50,20,23,...,28:24,116,7,8,15,16,12,28,-13,-1.08

In [11]:
#Get a list of the Column Names
df_2013_col_names = list(df_2013.columns)

In [12]:
#Column Datatypes?
df_2013.dtypes

Team                             object
Games                             int64
Win                               int64
Loss                              int64
Off.Rank                          int64
                                 ...
Fumbles.Lost                      int64
Interceptions.Thrown.y            int64
Turnovers.Lost                    int64
Turnover.Margin                   int64
Avg.Turnover.Margin.per.Game    float64
Length: 146, dtype: object

In [13]:
df_2013.isnull().sum()

Team                            0
Games                           0
Win                             0
Loss                            0
Off.Rank                        0
                               ..
Fumbles.Lost                    0
Interceptions.Thrown.y          0
Turnovers.Lost                  0
Turnover.Margin                 0
Avg.Turnover.Margin.per.Game    0
Length: 146, dtype: int64

In [14]:
#Try to determine which Stat/column has the most and least impact on Wins.

In [29]:
#Print only SEC Teams to the console
df_2013[df_2013['Team'].str.contains("")]

C:\Users\josrh\AppData\Local\Temp\ipykernel_16976\3636723126.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_2013[df_2013['Team'].str.contains("'()'")]

Empty DataFrame
Columns: [Team, Games, Win, Loss, Off.Rank, Off.Plays, Off.Yards, Off.Yards.Play, Off.TDs, Total.TDs, Off.Yards.per.Game, Def.Rank, Def.Plays, Yards.Allowed, Yards.Play.Allowed, Off.TDs.Allowed, Total.TDs.Allowed, Yards.Per.Game.Allowed, First.Down.Rank, First.Down.Runs, First.Down.Passes, First.Down.Penalties, First.Downs, First.Down.Def.Rank, Opp.First.Down.Runs, Opp.First.Down.Passes, Opp.First.Down.Penalties, Opp.First.Downs, X4th.Down.Rank, X4th.Attempts, X4th.Conversions, X4th.Percent, X4rd.Down.Def.Rank, Opp.4th.Conversion, Opp.4th.Attempt, Opponent.4th.Percent, Kickoff.Return.Rank, Kickoffs.Returned, Kickoff.Return.Yards, Kickoff.Return.Touchdowns, Avg.Yard.per.Kickoff.Return, Passing.Off.Rank, Pass.Attempts, Pass.Completions, Interceptions.Thrown.x, Pass.Yards, Pass.Yards.Attempt, Yards.Completion, Pass.Touchdowns, Pass.Yards.Per.Game, Pass.Def.Rank, Opp.Completions.Allowed, Opp.Pass.Attempts, Opp.Pass.Yds.Allowed, Opp.Pass.TDs.Allowed, Yards.Attempt.Allowed, Yards.Completion.Allowed, Pass.Yards.Per.Game.Allowed, Penalty.Rank, Penalties, Penalty.Yards, Penalty.Yards.Per.Game, Punt.Return.Rank, Punt.Returns, Net.Punt.Return.Yards, Punt.Return.Touchdowns, Avg.Yards.Per.Punt.Return, Punt.Return.Def.Rank, Opp.Punt.Returns, Opp.Net.Punt.Return.Yards, Opp.Punt.Return.Touchdowns.Allowed, Avg.Yards.Allowed.per.Punt.Return, Redzone.Off.Rank, Redzone.Attempts, Redzone.Rush.TD, Redzone.Pass.TD, Redzone.Field.Goals.Made, Redzone.Scores, Redzone.Points, Redzone.Def.Rank, Opp.Redzone.Attempts, Opp.Redzone.Rush.TD.Allowed, Opp.Redzone.Pass.Touchdowns.Allowed, Opp.Redzone.Field.Goals.Made, Opp.Redzone.Scores, Redzone.Points.Allowed, Rushing.Off.Rank, Rush.Attempts, Rush.Yds, Yards.Rush, Rushing.TD, Rushing.Yards.per.Game, Rushing.Def.Rank, Opp.Rush.Attempts, Opp.Rush.Yards.Alloweed, Yds.Rush.Allowed, Opp.Rush.Touchdowns.Allowed, Rush.Yards.Per.Game.Allowed, Sack.Rank, Sacks, ...]
Index: []

[0 rows x 146 columns]

In [30]:
#After finding that Ole Miss was missing, I wanted to figure out what other rows were missing the conference.
df_2013[df_2013['Team'].str.endswith("()")]

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Total.TDs,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
69,Ole Miss (),13,9,4,51,904,5448,6.03,45,49,...,28:14,27,10,22,32,10,15,25,7,0.54
73,Pittsburgh (),13,6,7,40,918,5660,6.17,52,52,...,33:49,95,4,10,14,12,7,19,-5,-0.38

In [38]:
#Now I want to edit those cells and add the correct coference
df_2013.iat[69,0] = 'Ole Miss (SEC)'

In [40]:
#I'll do the same to Pitt now
df_2013.iat[73,0] = 'Pittsburgh (ACC)'

In [41]:
#Now I'll get the SEC teams again
df_2013[df_2013['Team'].str.contains('SEC')]

,Team,Games,Win,Loss,Off.Rank,Off.Plays,Off.Yards,Off.Yards.Play,Off.TDs,Total.TDs,...,Average.Time.of.Possession.per.Game,Turnover.Rank,Fumbles.Recovered,Opponents.Intercepted,Turnovers.Gain,Fumbles.Lost,Interceptions.Thrown.y,Turnovers.Lost,Turnover.Margin,Avg.Turnover.Margin.per.Game
1,Alabama (SEC),14,12,2,17,1018,6783,6.66,67,68,...,31:45,71,9,11,20,12,10,22,-2,-0.14
4,Arkansas (SEC),13,7,6,60,916,5278,5.76,52,56,...,34:02,27,12,12,24,11,6,17,7,0.54
7,Auburn (SEC),13,8,5,16,939,6305,6.71,55,58,...,29:52,27,5,22,27,13,7,20,7,0.54
24,Florida (SEC),12,7,5,93,841,4411,5.24,40,44,...,29:55,30,14,16,30,10,14,24,6,0.50
26,Georgia (SEC),13,10,3,28,877,5951,6.79,62,70,...,29:16,4,13,16,29,7,6,13,16,1.23
38,Kentucky (SEC),12,5,7,79,849,4612,5.43,35,41,...,28:40,19,8,15,23,4,11,15,8,0.67
43,LSU (SEC),13,8,5,77,897,5037,5.62,42,46,...,33:08,48,10,10,20,8,9,17,3,0.23
54,Mississippi St. (SEC),13,10,3,8,1001,6679,6.67,60,64,...,29:37,59,7,16,23,11,12,23,0,0.00
55,Missouri (SEC),14,11,3,95,954,5138,5.39,42,48,...,28:59,20,13,12,25,3,13,16,9,0.64
69,Ole Miss (SEC),13,9,4,51,904,5448,6.03,45,49,...,28:14,27,10,22,32,10,15,25,7,0.54
79,South Carolina (SEC),13,7,6,33,947,5764,6.09,51,53,...,30:49,73,8,11,19,10,11,21,-2,-0.15
87,Tennessee (SEC),13,7,6,90,977,4817,4.93,43,45,...,30:14,53,8,16,24,8,14,22,2,0.15
89,Texas A&M (SEC),13,8,5,30,935,5920,6.33,59,60,...,26:15,105,8,5,13,5,15,20,-7,-0.54
103,Vanderbilt (SEC),12,3,9,122,740,3460,4.68,20,26,...,29:29,121,7,6,13,10,19,29,-16,-1.33

<h1>Success!</h1>

In [ ]:
#Next let's try to list the teams by conference